// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="aegis_shield_aegis_shield,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100ti-fgg484-1L,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.997000,HLS_SYN_LAT=19,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=26,HLS_SYN_LUT=68,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module aegis_shield (
        ap_clk,
        ap_rst_n,
        x_t_TVALID,
        u_t_TREADY,
        anx_in,
        x_t_TDATA,
        x_t_TREADY,
        x_t_TKEEP,
        x_t_TSTRB,
        x_t_TLAST,
        u_t_TDATA,
        u_t_TVALID,
        u_t_TKEEP,
        u_t_TSTRB,
        u_t_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input   x_t_TVALID;
input   u_t_TREADY;
input  [15:0] anx_in;
input  [15:0] x_t_TDATA;
output   x_t_TREADY;
input  [1:0] x_t_TKEEP;
input  [1:0] x_t_TSTRB;
input  [0:0] x_t_TLAST;
output  [15:0] u_t_TDATA;
output   u_t_TVALID;
output  [1:0] u_t_TKEEP;
output  [1:0] u_t_TSTRB;
output  [0:0] u_t_TLAST;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_enable_reg_pp0_iter1;
wire    regslice_both_u_t_V_data_V_U_apdone_blk;
reg    ap_enable_reg_pp0_iter2;
wire    ap_loop_exit_ready_pp0_iter2_reg;
wire   [0:0] icmp_ln21_fu_118_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    x_t_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    u_t_TDATA_blk_n;
reg   [15:0] p_0_reg_142;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [0:0] icmp_ln21_reg_147;
reg    ap_block_pp0_stage0_11001;
reg   [3:0] i_fu_72;
wire   [3:0] i_3_fu_124_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_2;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
reg   [0:0] ap_NS_fsm;
wire    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_continue_int;
wire    regslice_both_x_t_V_data_V_U_apdone_blk;
wire   [15:0] x_t_TDATA_int_regslice;
wire    x_t_TVALID_int_regslice;
reg    x_t_TREADY_int_regslice;
wire    regslice_both_x_t_V_data_V_U_ack_in;
wire    regslice_both_x_t_V_keep_V_U_apdone_blk;
wire   [1:0] x_t_TKEEP_int_regslice;
wire    regslice_both_x_t_V_keep_V_U_vld_out;
wire    regslice_both_x_t_V_keep_V_U_ack_in;
wire    regslice_both_x_t_V_strb_V_U_apdone_blk;
wire   [1:0] x_t_TSTRB_int_regslice;
wire    regslice_both_x_t_V_strb_V_U_vld_out;
wire    regslice_both_x_t_V_strb_V_U_ack_in;
wire    regslice_both_x_t_V_last_V_U_apdone_blk;
wire   [0:0] x_t_TLAST_int_regslice;
wire    regslice_both_x_t_V_last_V_U_vld_out;
wire    regslice_both_x_t_V_last_V_U_ack_in;
reg    u_t_TVALID_int_regslice;
wire    u_t_TREADY_int_regslice;
wire    regslice_both_u_t_V_data_V_U_vld_out;
wire    regslice_both_u_t_V_keep_V_U_apdone_blk;
wire    regslice_both_u_t_V_keep_V_U_ack_in_dummy;
wire    regslice_both_u_t_V_keep_V_U_vld_out;
wire    regslice_both_u_t_V_strb_V_U_apdone_blk;
wire    regslice_both_u_t_V_strb_V_U_ack_in_dummy;
wire    regslice_both_u_t_V_strb_V_U_vld_out;
wire    regslice_both_u_t_V_last_V_U_apdone_blk;
wire    regslice_both_u_t_V_last_V_U_ack_in_dummy;
wire    regslice_both_u_t_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_72 = 4'd0;
end

aegis_shield_flow_control_loop_pipe_no_ap_cont flow_control_loop_pipe_no_ap_cont_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(1'b1),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(1'b0),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(1'b0)
);

aegis_shield_regslice_both #(
    .DataWidth( 16 ))
regslice_both_x_t_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(x_t_TDATA),
    .vld_in(x_t_TVALID),
    .ack_in(regslice_both_x_t_V_data_V_U_ack_in),
    .data_out(x_t_TDATA_int_regslice),
    .vld_out(x_t_TVALID_int_regslice),
    .ack_out(x_t_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_t_V_data_V_U_apdone_blk)
);

aegis_shield_regslice_both #(
    .DataWidth( 2 ))
regslice_both_x_t_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(x_t_TKEEP),
    .vld_in(x_t_TVALID),
    .ack_in(regslice_both_x_t_V_keep_V_U_ack_in),
    .data_out(x_t_TKEEP_int_regslice),
    .vld_out(regslice_both_x_t_V_keep_V_U_vld_out),
    .ack_out(x_t_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_t_V_keep_V_U_apdone_blk)
);

aegis_shield_regslice_both #(
    .DataWidth( 2 ))
regslice_both_x_t_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(x_t_TSTRB),
    .vld_in(x_t_TVALID),
    .ack_in(regslice_both_x_t_V_strb_V_U_ack_in),
    .data_out(x_t_TSTRB_int_regslice),
    .vld_out(regslice_both_x_t_V_strb_V_U_vld_out),
    .ack_out(x_t_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_t_V_strb_V_U_apdone_blk)
);

aegis_shield_regslice_both #(
    .DataWidth( 1 ))
regslice_both_x_t_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(x_t_TLAST),
    .vld_in(x_t_TVALID),
    .ack_in(regslice_both_x_t_V_last_V_U_ack_in),
    .data_out(x_t_TLAST_int_regslice),
    .vld_out(regslice_both_x_t_V_last_V_U_vld_out),
    .ack_out(x_t_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_t_V_last_V_U_apdone_blk)
);

aegis_shield_regslice_both #(
    .DataWidth( 16 ))
regslice_both_u_t_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(p_0_reg_142),
    .vld_in(u_t_TVALID_int_regslice),
    .ack_in(u_t_TREADY_int_regslice),
    .data_out(u_t_TDATA),
    .vld_out(regslice_both_u_t_V_data_V_U_vld_out),
    .ack_out(u_t_TREADY),
    .apdone_blk(regslice_both_u_t_V_data_V_U_apdone_blk)
);

aegis_shield_regslice_both #(
    .DataWidth( 2 ))
regslice_both_u_t_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(2'd3),
    .vld_in(u_t_TVALID_int_regslice),
    .ack_in(regslice_both_u_t_V_keep_V_U_ack_in_dummy),
    .data_out(u_t_TKEEP),
    .vld_out(regslice_both_u_t_V_keep_V_U_vld_out),
    .ack_out(u_t_TREADY),
    .apdone_blk(regslice_both_u_t_V_keep_V_U_apdone_blk)
);

aegis_shield_regslice_both #(
    .DataWidth( 2 ))
regslice_both_u_t_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(2'd3),
    .vld_in(u_t_TVALID_int_regslice),
    .ack_in(regslice_both_u_t_V_strb_V_U_ack_in_dummy),
    .data_out(u_t_TSTRB),
    .vld_out(regslice_both_u_t_V_strb_V_U_vld_out),
    .ack_out(u_t_TREADY),
    .apdone_blk(regslice_both_u_t_V_strb_V_U_apdone_blk)
);

aegis_shield_regslice_both #(
    .DataWidth( 1 ))
regslice_both_u_t_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(icmp_ln21_reg_147),
    .vld_in(u_t_TVALID_int_regslice),
    .ack_in(regslice_both_u_t_V_last_V_U_ack_in_dummy),
    .data_out(u_t_TLAST),
    .vld_out(regslice_both_u_t_V_last_V_U_vld_out),
    .ack_out(u_t_TREADY),
    .apdone_blk(regslice_both_u_t_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_72 <= i_3_fu_124_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln21_reg_147 <= icmp_ln21_fu_118_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_reg_142 <= x_t_TDATA_int_regslice;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_118_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

assign ap_idle_pp0 = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_72;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        u_t_TDATA_blk_n = u_t_TREADY_int_regslice;
    end else begin
        u_t_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_t_TVALID_int_regslice = 1'b1;
    end else begin
        u_t_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_t_TDATA_blk_n = x_t_TVALID_int_regslice;
    end else begin
        x_t_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_t_TREADY_int_regslice = 1'b1;
    end else begin
        x_t_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_u_t_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (u_t_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (u_t_TREADY_int_regslice == 1'b0)) | ((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (x_t_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_u_t_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_u_t_V_data_V_U_apdone_blk == 1'b1) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (u_t_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (u_t_TREADY_int_regslice == 1'b0)) | ((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (x_t_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_u_t_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (u_t_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (u_t_TREADY_int_regslice == 1'b0)) | ((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (x_t_TVALID_int_regslice == 1'b0)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_u_t_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_u_t_V_data_V_U_apdone_blk == 1'b1) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (u_t_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (u_t_TREADY_int_regslice == 1'b0)) | ((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (x_t_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_u_t_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (u_t_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (u_t_TREADY_int_regslice == 1'b0)) | ((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (x_t_TVALID_int_regslice == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready_pp0_iter2_reg = 1'b0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign i_3_fu_124_p2 = (ap_sig_allocacmp_i_2 + 4'd1);

assign icmp_ln21_fu_118_p2 = ((ap_sig_allocacmp_i_2 == 4'd15) ? 1'b1 : 1'b0);

assign u_t_TVALID = regslice_both_u_t_V_data_V_U_vld_out;

assign x_t_TREADY = regslice_both_x_t_V_data_V_U_ack_in;


reg find_kernel_block = 0;
// synthesis translate_off
`include "aegis_shield_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //aegis_shield

