# =============================================================================
# aegis_ax7102_usb.xdc — Physical Constraints for Aegis-Chip USB build
# =============================================================================
# Board   : ALINX AX7102 Rev 1.1
# FPGA    : XC7A100T-2FGG484I
# Top     : aegis_top_usb
# Transport: CY68013A EZ-USB FX2LP slave-FIFO (16-bit parallel, Bank14/15)
#
# This file replaces the Ethernet sections of aegis_ax7102.xdc.
# Pin sources:
#   USB (CY68013A) : vendor usb_test/usb_test/constrs_1/new/usb.xdc
#   All others     : AX7102_UG.pdf
# =============================================================================

# -----------------------------------------------------------------------------
# 1. CONFIGURATION
# -----------------------------------------------------------------------------
set_property CFGBVS         VCCO  [current_design]
set_property CONFIG_VOLTAGE  3.3  [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4    [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE   33   [current_design]
set_property BITSTREAM.GENERAL.COMPRESS    TRUE [current_design]

# =============================================================================
# 2. SYSTEM CLOCK — 200 MHz LVDS (Bank34, DIFF_SSTL15)
# =============================================================================
set_property PACKAGE_PIN  R4          [get_ports sys_clk_p]
set_property PACKAGE_PIN  T4          [get_ports sys_clk_n]
set_property IOSTANDARD   DIFF_SSTL15 [get_ports sys_clk_p]
set_property IOSTANDARD   DIFF_SSTL15 [get_ports sys_clk_n]

create_clock -name clk200 -period 5.000 -waveform {0.000 2.500} \
    [get_ports sys_clk_p]

# 100 MHz core clock generated by ÷2 flip-flop in aegis_top_usb
create_generated_clock -name clk100 -source [get_ports sys_clk_p] \
    -divide_by 2 [get_pins sys_clk_div2_reg/Q]

# =============================================================================
# 3. RESET BUTTON — active-low (Bank34, LVCMOS15)
# =============================================================================
set_property PACKAGE_PIN  T6       [get_ports reset_n]
set_property IOSTANDARD   LVCMOS15 [get_ports reset_n]
set_false_path -from [get_ports reset_n]

# =============================================================================
# 4. CY68013A EZ-USB FX2LP — Slave FIFO interface (Bank14/15, LVCMOS33)
#
# Pin assignments from vendor usb_test/usb_test/constrs_1/new/usb.xdc
# =============================================================================

set_property IOSTANDARD LVCMOS33 [get_ports usb_slcs]
set_property PACKAGE_PIN P16     [get_ports usb_slcs]

set_property IOSTANDARD LVCMOS33 [get_ports usb_sloe]
set_property PACKAGE_PIN N13     [get_ports usb_sloe]

set_property IOSTANDARD LVCMOS33 [get_ports usb_slrd]
set_property PACKAGE_PIN P19     [get_ports usb_slrd]

set_property IOSTANDARD LVCMOS33 [get_ports usb_slwr]
set_property PACKAGE_PIN R19     [get_ports usb_slwr]

set_property IOSTANDARD LVCMOS33 [get_ports usb_flaga]
set_property PACKAGE_PIN R18     [get_ports usb_flaga]

set_property IOSTANDARD LVCMOS33 [get_ports usb_flagb]
set_property PACKAGE_PIN R14     [get_ports usb_flagb]

set_property IOSTANDARD LVCMOS33 [get_ports usb_flagc]
set_property PACKAGE_PIN P14     [get_ports usb_flagc]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fifoaddr[0]}]
set_property PACKAGE_PIN N14     [get_ports {usb_fifoaddr[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fifoaddr[1]}]
set_property PACKAGE_PIN N15     [get_ports {usb_fifoaddr[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[0]}]
set_property PACKAGE_PIN Y22     [get_ports {usb_fd[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[1]}]
set_property PACKAGE_PIN W20     [get_ports {usb_fd[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[2]}]
set_property PACKAGE_PIN W19     [get_ports {usb_fd[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[3]}]
set_property PACKAGE_PIN Y19     [get_ports {usb_fd[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[4]}]
set_property PACKAGE_PIN Y18     [get_ports {usb_fd[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[5]}]
set_property PACKAGE_PIN V22     [get_ports {usb_fd[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[6]}]
set_property PACKAGE_PIN U22     [get_ports {usb_fd[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[7]}]
set_property PACKAGE_PIN T18     [get_ports {usb_fd[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[8]}]
set_property PACKAGE_PIN R17     [get_ports {usb_fd[8]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[9]}]
set_property PACKAGE_PIN R16     [get_ports {usb_fd[9]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[10]}]
set_property PACKAGE_PIN P15     [get_ports {usb_fd[10]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[11]}]
set_property PACKAGE_PIN N17     [get_ports {usb_fd[11]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[12]}]
set_property PACKAGE_PIN P17     [get_ports {usb_fd[12]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[13]}]
set_property PACKAGE_PIN U16     [get_ports {usb_fd[13]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[14]}]
set_property PACKAGE_PIN T16     [get_ports {usb_fd[14]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[15]}]
set_property PACKAGE_PIN U17     [get_ports {usb_fd[15]}]

# USB control signals are register outputs with conservative timing —
# treat them as multi-cycle relative to the 100 MHz core clock.
# The CY68013A FX2LP is not directly clocked by clk100; all timing is
# achieved through cycle-counted state-machine delays in aegis_usb_bridge.
set_false_path -to   [get_ports {usb_slcs usb_sloe usb_slrd usb_slwr}]
set_false_path -to   [get_ports {usb_fifoaddr[*]}]
set_false_path -to   [get_ports {usb_fd[*]}]
set_false_path -from [get_ports {usb_flaga usb_flagb usb_flagc}]
set_false_path -from [get_ports {usb_fd[*]}]

# =============================================================================
# 5. EXPANSION-BOARD USER BUTTONS — KEY1..KEY4 (Bank14/15, LVCMOS33)
# =============================================================================
set_property PACKAGE_PIN  B18      [get_ports {key_n[0]}]
set_property PACKAGE_PIN  B17      [get_ports {key_n[1]}]
set_property PACKAGE_PIN  A16      [get_ports {key_n[2]}]
set_property PACKAGE_PIN  A15      [get_ports {key_n[3]}]
set_property IOSTANDARD   LVCMOS33 [get_ports {key_n[*]}]
set_false_path -from [get_ports {key_n[*]}]

# =============================================================================
# 6. EXPANSION-BOARD USER LEDs — LED1..LED4 (Bank15/14, LVCMOS33)
# =============================================================================
set_property PACKAGE_PIN  C17      [get_ports {led_n[0]}]
set_property PACKAGE_PIN  D17      [get_ports {led_n[1]}]
set_property PACKAGE_PIN  V20      [get_ports {led_n[2]}]
set_property PACKAGE_PIN  U20      [get_ports {led_n[3]}]
set_property IOSTANDARD   LVCMOS33 [get_ports {led_n[*]}]
set_false_path -to [get_ports {led_n[*]}]

# =============================================================================
# 7. XADC ANALOG INPUTS — VP/VN dedicated pair (CON1 PIN53/51)
# =============================================================================
set_property PACKAGE_PIN  L10 [get_ports vauxp_ecg]
set_property PACKAGE_PIN  M9  [get_ports vauxn_ecg]
# VP/VN are dedicated analog pads — no IOSTANDARD constraint required
