# =============================================================================
# aegis_ax7102.xdc — Physical Constraints for Aegis-Chip on AX7102 Board
# =============================================================================
# Board   : ALINX AX7102 Rev 1.1
# FPGA    : XC7A100T-2FGG484I  (Artix-7, 484-pin BGA, speed-grade -2, industrial)
# Source  : AX7102_UG.pdf (Sections 三, 六, 七, 七[USB-UART])
#
# Bank voltage summary (from AX7102_UG.pdf p.10):
#   Bank 0        : 3.3 V  (QSPI Flash, config)
#   Bank 13, 14   : 3.3 V  (UART, Ethernet, expansion CON2)
#   Bank 15, 16   : 3.3 V  (SFP, expansion CON3, CON1-partial)
#   Bank 34, 35   : 1.5 V  (DDR3, system clock, reset, core LED)
# =============================================================================

# -----------------------------------------------------------------------------
# 1. CONFIGURATION PROPERTIES
#    CFGBVS must match the voltage on the configuration pins.
#    Bank 0 (config bank) is powered at 3.3 V on AX7102.
# -----------------------------------------------------------------------------
set_property CFGBVS        VCCO        [current_design]
set_property CONFIG_VOLTAGE 3.3        [current_design]

# Vivado may warn about BITSTREAM.CONFIG.SPI_BUSWIDTH; override for QSPI:
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4          [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE  33          [current_design]
set_property BITSTREAM.GENERAL.COMPRESS   TRUE        [current_design]

# =============================================================================
# 2. SYSTEM CLOCK — 200 MHz LVDS differential (SiTime SiT9102-200.00MHz)
#    Connected to Bank34 MRCC pins R4 (P) and T4 (N).
#    Bank34 Vcco = 1.5 V  →  DIFF_SSTL15 standard.
# =============================================================================
set_property PACKAGE_PIN  R4           [get_ports sys_clk_p]
set_property PACKAGE_PIN  T4           [get_ports sys_clk_n]
set_property IOSTANDARD   DIFF_SSTL15  [get_ports sys_clk_p]
set_property IOSTANDARD   DIFF_SSTL15  [get_ports sys_clk_n]

# Primary timing constraint — 5.000 ns = 200 MHz
create_clock -name clk200 -period 5.000 -waveform {0.000 2.500} \
    [get_ports sys_clk_p]

# Core logic clock generated by a divide-by-2 flip-flop in rtl/aegis_top.v
create_generated_clock -name clk100 -source [get_ports sys_clk_p] \
    -divide_by 2 [get_pins sys_clk_div2_reg/Q]

# PHY-ready CDC: clk100 -> eth_rx_clk enters a 2-FF synchronizer in rtl/aegis_top.v.
set_false_path -from [get_clocks clk100] -to [get_pins phy_ready_meta_reg/D]

# =============================================================================
# 3. RESET BUTTON — active-low push-button
#    Connected to Bank34 IO_L17N_T2_34 (pin T6).
#    Bank34 Vcco = 1.5 V → LVCMOS15.  High = idle, Low = reset pressed.
# =============================================================================
set_property PACKAGE_PIN  T6           [get_ports reset_n]
set_property IOSTANDARD   LVCMOS15     [get_ports reset_n]

# Treat reset as asynchronous; relax timing (it's double-flopped internally)
set_false_path -from [get_ports reset_n]

# =============================================================================
# 4. UART (USB ↔ CP2102GM on expansion board, Micro-USB J3)
#    Connected through expansion connector to Bank13 (3.3 V).
#    UART1_RXD = Y12  (data from CP2102 TXD  →  FPGA receives)
#    UART1_TXD = Y11  (data from FPGA TX     →  CP2102 RXD)
# =============================================================================
set_property PACKAGE_PIN  Y12          [get_ports uart_rxd]
set_property IOSTANDARD   LVCMOS33     [get_ports uart_rxd]

set_property PACKAGE_PIN  Y11          [get_ports uart_txd]
set_property IOSTANDARD   LVCMOS33     [get_ports uart_txd]

# UART is an async interface — false-path both directions
set_false_path -from [get_ports uart_rxd]
set_false_path -to   [get_ports uart_txd]

# =============================================================================
# 4b. Ethernet GMII interface (RTL8211EG PHY)
#     Confirmed against the board guide and demo XDC.
#     TX path:
#       e_txc   = J17   (input from PHY / compatibility clock)
#       e_gtxc  = L18   (output to PHY)
#       e_txen  = M16
#       e_txer  = M13
#       e_txd   = M15, L14, K16, L16, K17, L20, L19, L13
#     RX path:
#       e_rxc   = K18
#       e_rxdv  = M22
#       e_rxer  = N19
#       e_rxd   = N22, H18, H17, K19, M21, L21, N20, M20
#     MDIO/MDC:
#       e_mdio  = V10
#       e_mdc   = W10
#       e_reset = L15  (PHY reset, active-low at the PHY, driven high here to release)
# =============================================================================
set_property PACKAGE_PIN  V10         [get_ports e_mdio]
set_property IOSTANDARD   LVCMOS33    [get_ports e_mdio]
set_property PACKAGE_PIN  W10         [get_ports e_mdc]
set_property IOSTANDARD   LVCMOS33    [get_ports e_mdc]
set_property PULLUP       true        [get_ports e_mdc]
set_property PULLUP       true        [get_ports e_mdio]
set_property SLEW         SLOW        [get_ports e_mdio]

set_property PACKAGE_PIN  K18         [get_ports e_rxc]
set_property IOSTANDARD   LVCMOS33    [get_ports e_rxc]
create_clock -name eth_rx_clk -period 8.000 [get_ports e_rxc]

set_property PACKAGE_PIN  M22         [get_ports e_rxdv]
set_property IOSTANDARD   LVCMOS33    [get_ports e_rxdv]
set_property PACKAGE_PIN  N19         [get_ports e_rxer]
set_property IOSTANDARD   LVCMOS33    [get_ports e_rxer]

set_property PACKAGE_PIN  N22         [get_ports {e_rxd[0]}]
set_property PACKAGE_PIN  H18         [get_ports {e_rxd[1]}]
set_property PACKAGE_PIN  H17         [get_ports {e_rxd[2]}]
set_property PACKAGE_PIN  K19         [get_ports {e_rxd[3]}]
set_property PACKAGE_PIN  M21         [get_ports {e_rxd[4]}]
set_property PACKAGE_PIN  L21         [get_ports {e_rxd[5]}]
set_property PACKAGE_PIN  N20         [get_ports {e_rxd[6]}]
set_property PACKAGE_PIN  M20         [get_ports {e_rxd[7]}]
set_property IOSTANDARD   LVCMOS33    [get_ports {e_rxd[*]}]

set_property PACKAGE_PIN  J17         [get_ports e_txc]
set_property IOSTANDARD   LVCMOS33    [get_ports e_txc]
set_property PACKAGE_PIN  L18         [get_ports e_gtxc]
set_property IOSTANDARD   LVCMOS33    [get_ports e_gtxc]
set_property PACKAGE_PIN  M16         [get_ports e_txen]
set_property IOSTANDARD   LVCMOS33    [get_ports e_txen]
set_property PACKAGE_PIN  M13         [get_ports e_txer]
set_property IOSTANDARD   LVCMOS33    [get_ports e_txer]

set_property PACKAGE_PIN  M15         [get_ports {e_txd[0]}]
set_property PACKAGE_PIN  L14         [get_ports {e_txd[1]}]
set_property PACKAGE_PIN  K16         [get_ports {e_txd[2]}]
set_property PACKAGE_PIN  L16         [get_ports {e_txd[3]}]
set_property PACKAGE_PIN  K17         [get_ports {e_txd[4]}]
set_property PACKAGE_PIN  L20         [get_ports {e_txd[5]}]
set_property PACKAGE_PIN  L19         [get_ports {e_txd[6]}]
set_property PACKAGE_PIN  L13         [get_ports {e_txd[7]}]
set_property IOSTANDARD   LVCMOS33    [get_ports {e_txd[*]}]

set_property PACKAGE_PIN  L15         [get_ports e_reset]
set_property IOSTANDARD   LVCMOS33    [get_ports e_reset]

set_false_path -from [get_clocks clk200] -to [get_clocks eth_rx_clk]
set_false_path -from [get_clocks eth_rx_clk] -to [get_clocks clk200]

# =============================================================================
# 5. EXPANSION-BOARD USER BUTTONS — KEY1..KEY4
#    Active-LOW: key_n=0 when pressed, pull-up to 3.3 V (AX7102_UG p.54).
#    Bank14/15, LVCMOS33.
# =============================================================================
set_property PACKAGE_PIN  B18         [get_ports {key_n[0]}]   ;# KEY1
set_property PACKAGE_PIN  B17         [get_ports {key_n[1]}]   ;# KEY2
set_property PACKAGE_PIN  A16         [get_ports {key_n[2]}]   ;# KEY3
set_property PACKAGE_PIN  A15         [get_ports {key_n[3]}]   ;# KEY4
set_property IOSTANDARD   LVCMOS33    [get_ports {key_n[*]}]

# Debouncer handles all async edges; relax timing for button inputs
set_false_path -from [get_ports {key_n[*]}]

# =============================================================================
# 6. EXPANSION-BOARD USER LEDs — LED1..LED4
#    Active-LOW: led_n=0 → LED ON  (AX7102_UG p.55).
#    Bank15/14, LVCMOS33.
#    LED1 mirrors KEY1, LED2→KEY2, LED3→KEY3, LED4→KEY4.
# =============================================================================
set_property PACKAGE_PIN  C17         [get_ports {led_n[0]}]   ;# LED1
set_property PACKAGE_PIN  D17         [get_ports {led_n[1]}]   ;# LED2
set_property PACKAGE_PIN  V20         [get_ports {led_n[2]}]   ;# LED3
set_property PACKAGE_PIN  U20         [get_ports {led_n[3]}]   ;# LED4
set_property IOSTANDARD   LVCMOS33    [get_ports {led_n[*]}]

set_false_path -to [get_ports {led_n[*]}]

# =============================================================================
# 7. CORE-BOARD USER LED (LED1 on core board — not the expansion LEDs above)
#    Pin W5, Bank34, 1.5 V.  Currently unused; reserved for future heartbeat.
# =============================================================================
# set_property PACKAGE_PIN  W5           [get_ports core_led]
# set_property IOSTANDARD   LVCMOS15     [get_ports core_led]

# =============================================================================
# 8. XADC ANALOG INPUTS — dedicated VP/VN pair (CON1 PIN53/PIN51)
#    VP  = L10  (XADC_VP, dedicated positive analog input)
#    VN  = M9   (XADC_VN, dedicated negative analog input)
#    These are purely analog pins — no IOSTANDARD constraint required.
#    They are exposed on the core board's CON1 expansion header.
# =============================================================================
set_property PACKAGE_PIN  L10          [get_ports vauxp_ecg]
set_property PACKAGE_PIN  M9           [get_ports vauxn_ecg]
# VP/VN are dedicated analog — no IOSTANDARD

# --------------------------------------------------------------------------
# VAUXP[1]/VAUXN[1] for EDA channel:
#   TODO: Confirm exact FPGA ball numbers for VAUXP[1]/VAUXN[1] in the
#   FGG484 package from the Xilinx Artix-7 package file (DS181 Table).
#   Candidate pins on CON1 Bank16 (3.3V): F13 (B16_L1_P), F14 (B16_L1_N)
#   Uncomment when confirmed:
#
# set_property PACKAGE_PIN  F13         [get_ports vauxp_eda]
# set_property PACKAGE_PIN  F14         [get_ports vauxn_eda]
# set_property IOSTANDARD   LVCMOS33    [get_ports vauxp_eda]
# set_property IOSTANDARD   LVCMOS33    [get_ports vauxn_eda]
# --------------------------------------------------------------------------

# =============================================================================
# 9. DERIVED CLOCK CONSTRAINTS
#    Vivado auto-derives clocks from the primary create_clock above.
#    If a PLL/MMCM is added later to scale to other frequencies, add
#    create_generated_clock entries here for those outputs.
# =============================================================================

# =============================================================================
# 10. PBLOCK / AREA CONSTRAINTS (optional — add if timing fails)
#    Example: constrain aegis_shield DSP to centre of device for short paths.
#
# create_pblock pb_shield
# add_cells_to_pblock [get_pblocks pb_shield] [get_cells u_aegis_shield]
# resize_pblock [get_pblocks pb_shield] -add {SLICE_X50Y50:SLICE_X99Y149}
# =============================================================================
