-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity aegis_shield is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    x_t_TVALID : IN STD_LOGIC;
    u_t_TREADY : IN STD_LOGIC;
    anx_in : IN STD_LOGIC_VECTOR (15 downto 0);
    x_t_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    x_t_TREADY : OUT STD_LOGIC;
    x_t_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    x_t_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    x_t_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    u_t_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    u_t_TVALID : OUT STD_LOGIC;
    u_t_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
    u_t_TSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    u_t_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of aegis_shield is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "aegis_shield_aegis_shield,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100ti-fgg484-1L,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.997000,HLS_SYN_LAT=19,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=26,HLS_SYN_LUT=68,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal regslice_both_u_t_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal icmp_ln21_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal x_t_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal u_t_TDATA_blk_n : STD_LOGIC;
    signal p_0_reg_142 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal icmp_ln21_reg_147 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_72 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal i_3_fu_124_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_continue_int : STD_LOGIC;
    signal regslice_both_x_t_V_data_V_U_apdone_blk : STD_LOGIC;
    signal x_t_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal x_t_TVALID_int_regslice : STD_LOGIC;
    signal x_t_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_x_t_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_t_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal x_t_TKEEP_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_x_t_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_t_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_t_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal x_t_TSTRB_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_x_t_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_t_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_t_V_last_V_U_apdone_blk : STD_LOGIC;
    signal x_t_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_x_t_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_t_V_last_V_U_ack_in : STD_LOGIC;
    signal u_t_TVALID_int_regslice : STD_LOGIC;
    signal u_t_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_u_t_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_u_t_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_u_t_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_u_t_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_u_t_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_u_t_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_u_t_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_u_t_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_u_t_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_u_t_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component aegis_shield_flow_control_loop_pipe_no_ap_cont IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;


    component aegis_shield_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_no_ap_cont_U : component aegis_shield_flow_control_loop_pipe_no_ap_cont
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => ap_const_logic_1,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_const_logic_0,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_const_logic_0);

    regslice_both_x_t_V_data_V_U : component aegis_shield_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_t_TDATA,
        vld_in => x_t_TVALID,
        ack_in => regslice_both_x_t_V_data_V_U_ack_in,
        data_out => x_t_TDATA_int_regslice,
        vld_out => x_t_TVALID_int_regslice,
        ack_out => x_t_TREADY_int_regslice,
        apdone_blk => regslice_both_x_t_V_data_V_U_apdone_blk);

    regslice_both_x_t_V_keep_V_U : component aegis_shield_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_t_TKEEP,
        vld_in => x_t_TVALID,
        ack_in => regslice_both_x_t_V_keep_V_U_ack_in,
        data_out => x_t_TKEEP_int_regslice,
        vld_out => regslice_both_x_t_V_keep_V_U_vld_out,
        ack_out => x_t_TREADY_int_regslice,
        apdone_blk => regslice_both_x_t_V_keep_V_U_apdone_blk);

    regslice_both_x_t_V_strb_V_U : component aegis_shield_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_t_TSTRB,
        vld_in => x_t_TVALID,
        ack_in => regslice_both_x_t_V_strb_V_U_ack_in,
        data_out => x_t_TSTRB_int_regslice,
        vld_out => regslice_both_x_t_V_strb_V_U_vld_out,
        ack_out => x_t_TREADY_int_regslice,
        apdone_blk => regslice_both_x_t_V_strb_V_U_apdone_blk);

    regslice_both_x_t_V_last_V_U : component aegis_shield_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_t_TLAST,
        vld_in => x_t_TVALID,
        ack_in => regslice_both_x_t_V_last_V_U_ack_in,
        data_out => x_t_TLAST_int_regslice,
        vld_out => regslice_both_x_t_V_last_V_U_vld_out,
        ack_out => x_t_TREADY_int_regslice,
        apdone_blk => regslice_both_x_t_V_last_V_U_apdone_blk);

    regslice_both_u_t_V_data_V_U : component aegis_shield_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => p_0_reg_142,
        vld_in => u_t_TVALID_int_regslice,
        ack_in => u_t_TREADY_int_regslice,
        data_out => u_t_TDATA,
        vld_out => regslice_both_u_t_V_data_V_U_vld_out,
        ack_out => u_t_TREADY,
        apdone_blk => regslice_both_u_t_V_data_V_U_apdone_blk);

    regslice_both_u_t_V_keep_V_U : component aegis_shield_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv2_3,
        vld_in => u_t_TVALID_int_regslice,
        ack_in => regslice_both_u_t_V_keep_V_U_ack_in_dummy,
        data_out => u_t_TKEEP,
        vld_out => regslice_both_u_t_V_keep_V_U_vld_out,
        ack_out => u_t_TREADY,
        apdone_blk => regslice_both_u_t_V_keep_V_U_apdone_blk);

    regslice_both_u_t_V_strb_V_U : component aegis_shield_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv2_3,
        vld_in => u_t_TVALID_int_regslice,
        ack_in => regslice_both_u_t_V_strb_V_U_ack_in_dummy,
        data_out => u_t_TSTRB,
        vld_out => regslice_both_u_t_V_strb_V_U_vld_out,
        ack_out => u_t_TREADY,
        apdone_blk => regslice_both_u_t_V_strb_V_U_apdone_blk);

    regslice_both_u_t_V_last_V_U : component aegis_shield_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => icmp_ln21_reg_147,
        vld_in => u_t_TVALID_int_regslice,
        ack_in => regslice_both_u_t_V_last_V_U_ack_in_dummy,
        data_out => u_t_TLAST,
        vld_out => regslice_both_u_t_V_last_V_U_vld_out,
        ack_out => u_t_TREADY,
        apdone_blk => regslice_both_u_t_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                i_fu_72 <= i_3_fu_124_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln21_reg_147 <= icmp_ln21_fu_118_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                p_0_reg_142 <= x_t_TDATA_int_regslice;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter1, regslice_both_u_t_V_data_V_U_apdone_blk, ap_enable_reg_pp0_iter2, ap_loop_exit_ready_pp0_iter2_reg, x_t_TVALID_int_regslice, u_t_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (regslice_both_u_t_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (u_t_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (u_t_TREADY_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (x_t_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter1, regslice_both_u_t_V_data_V_U_apdone_blk, ap_enable_reg_pp0_iter2, ap_loop_exit_ready_pp0_iter2_reg, x_t_TVALID_int_regslice, u_t_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (regslice_both_u_t_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_u_t_V_data_V_U_apdone_blk = ap_const_logic_1) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (u_t_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (u_t_TREADY_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (x_t_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter1, regslice_both_u_t_V_data_V_U_apdone_blk, ap_enable_reg_pp0_iter2, ap_loop_exit_ready_pp0_iter2_reg, x_t_TVALID_int_regslice, u_t_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (regslice_both_u_t_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (u_t_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (u_t_TREADY_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (x_t_TVALID_int_regslice = ap_const_logic_0)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter1, regslice_both_u_t_V_data_V_U_apdone_blk, ap_enable_reg_pp0_iter2, ap_loop_exit_ready_pp0_iter2_reg, x_t_TVALID_int_regslice, u_t_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (regslice_both_u_t_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_u_t_V_data_V_U_apdone_blk = ap_const_logic_1) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (u_t_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (u_t_TREADY_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (x_t_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_subdone_grp1_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter1, regslice_both_u_t_V_data_V_U_apdone_blk, ap_enable_reg_pp0_iter2, ap_loop_exit_ready_pp0_iter2_reg, x_t_TVALID_int_regslice, u_t_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone_grp1 <= (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (regslice_both_u_t_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (u_t_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (u_t_TREADY_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (x_t_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln21_fu_118_p2)
    begin
        if (((icmp_ln21_fu_118_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_idle_pp0 <= ap_const_logic_0;
    ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, i_fu_72, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_72;
        end if; 
    end process;

    i_3_fu_124_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv4_1));
    icmp_ln21_fu_118_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv4_F) else "0";

    u_t_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_grp1, u_t_TREADY_int_regslice)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            u_t_TDATA_blk_n <= u_t_TREADY_int_regslice;
        else 
            u_t_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    u_t_TVALID <= regslice_both_u_t_V_data_V_U_vld_out;

    u_t_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            u_t_TVALID_int_regslice <= ap_const_logic_1;
        else 
            u_t_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    x_t_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_block_pp0_stage0_grp1, x_t_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_t_TDATA_blk_n <= x_t_TVALID_int_regslice;
        else 
            x_t_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    x_t_TREADY <= regslice_both_x_t_V_data_V_U_ack_in;

    x_t_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_t_TREADY_int_regslice <= ap_const_logic_1;
        else 
            x_t_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
