## AX7102 Rev 1.1 constraints for alternate Ethernet TX-map smoke test
## Keeps the proven board clocks/UART/RX pins, but swaps TX-side assignments
## to validate the older handover map hypothesis.

set_property PACKAGE_PIN U18 [get_ports sys_clk_p]
set_property IOSTANDARD LVDS_25 [get_ports sys_clk_p]
set_property PACKAGE_PIN U19 [get_ports sys_clk_n]
set_property IOSTANDARD LVDS_25 [get_ports sys_clk_n]
create_clock -period 5.000 -name sys_clk -waveform {0.000 2.500} [get_ports sys_clk_p]

set_property PACKAGE_PIN P20 [get_ports reset_n]
set_property IOSTANDARD LVCMOS25 [get_ports reset_n]

set_property PACKAGE_PIN Y12 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS25 [get_ports uart_rxd]
set_property PACKAGE_PIN Y11 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS25 [get_ports uart_txd]

set_property PACKAGE_PIN W3 [get_ports vauxp_ecg]
set_property IOSTANDARD LVCMOS25 [get_ports vauxp_ecg]
set_property PACKAGE_PIN V3 [get_ports vauxn_ecg]
set_property IOSTANDARD LVCMOS25 [get_ports vauxn_ecg]
set_property PACKAGE_PIN W5 [get_ports vauxp_eda]
set_property IOSTANDARD LVCMOS25 [get_ports vauxp_eda]
set_property PACKAGE_PIN V5 [get_ports vauxn_eda]
set_property IOSTANDARD LVCMOS25 [get_ports vauxn_eda]

set_property PACKAGE_PIN H8 [get_ports {key_n[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {key_n[0]}]
set_property PACKAGE_PIN K8 [get_ports {key_n[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {key_n[1]}]
set_property PACKAGE_PIN K9 [get_ports {key_n[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {key_n[2]}]
set_property PACKAGE_PIN L9 [get_ports {key_n[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {key_n[3]}]

set_property PACKAGE_PIN E6 [get_ports {led_n[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_n[0]}]
set_property PACKAGE_PIN E7 [get_ports {led_n[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_n[1]}]
set_property PACKAGE_PIN D5 [get_ports {led_n[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_n[2]}]
set_property PACKAGE_PIN C5 [get_ports {led_n[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_n[3]}]

set_property PACKAGE_PIN M20 [get_ports e_reset]
set_property IOSTANDARD LVCMOS25 [get_ports e_reset]
set_property PACKAGE_PIN P17 [get_ports e_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports e_mdc]
set_property PACKAGE_PIN P18 [get_ports e_mdio]
set_property IOSTANDARD LVCMOS25 [get_ports e_mdio]
set_property PULLUP true [get_ports e_mdio]

set_property PACKAGE_PIN K18 [get_ports e_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports e_rxc]
create_clock -period 8.000 -name e_rxc_clk -waveform {0.000 4.000} [get_ports e_rxc]

set_property PACKAGE_PIN L18 [get_ports e_gtxc]
set_property IOSTANDARD LVCMOS25 [get_ports e_gtxc]
set_property SLEW FAST [get_ports e_gtxc]
set_property DRIVE 12 [get_ports e_gtxc]

set_property PACKAGE_PIN N20 [get_ports e_rxdv]
set_property IOSTANDARD LVCMOS25 [get_ports e_rxdv]
set_property PACKAGE_PIN N19 [get_ports e_rxer]
set_property IOSTANDARD LVCMOS25 [get_ports e_rxer]
set_property PACKAGE_PIN P14 [get_ports {e_rxd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_rxd[0]}]
set_property PACKAGE_PIN R18 [get_ports {e_rxd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_rxd[1]}]
set_property PACKAGE_PIN R20 [get_ports {e_rxd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_rxd[2]}]
set_property PACKAGE_PIN P19 [get_ports {e_rxd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_rxd[3]}]
set_property PACKAGE_PIN M18 [get_ports {e_rxd[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_rxd[4]}]
set_property PACKAGE_PIN M19 [get_ports {e_rxd[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_rxd[5]}]
set_property PACKAGE_PIN P15 [get_ports {e_rxd[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_rxd[6]}]
set_property PACKAGE_PIN R19 [get_ports {e_rxd[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_rxd[7]}]

## Alternate TX hypothesis from older handover notes
set_property PACKAGE_PIN M15 [get_ports e_txen]
set_property IOSTANDARD LVCMOS25 [get_ports e_txen]
set_property SLEW FAST [get_ports e_txen]
set_property DRIVE 12 [get_ports e_txen]

set_property PACKAGE_PIN M13 [get_ports e_txer]
set_property IOSTANDARD LVCMOS25 [get_ports e_txer]
set_property SLEW FAST [get_ports e_txer]
set_property DRIVE 12 [get_ports e_txer]

set_property PACKAGE_PIN L14 [get_ports {e_txd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_txd[0]}]
set_property SLEW FAST [get_ports {e_txd[0]}]
set_property DRIVE 12 [get_ports {e_txd[0]}]
set_property PACKAGE_PIN K16 [get_ports {e_txd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_txd[1]}]
set_property SLEW FAST [get_ports {e_txd[1]}]
set_property DRIVE 12 [get_ports {e_txd[1]}]
set_property PACKAGE_PIN L16 [get_ports {e_txd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_txd[2]}]
set_property SLEW FAST [get_ports {e_txd[2]}]
set_property DRIVE 12 [get_ports {e_txd[2]}]
set_property PACKAGE_PIN K17 [get_ports {e_txd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_txd[3]}]
set_property SLEW FAST [get_ports {e_txd[3]}]
set_property DRIVE 12 [get_ports {e_txd[3]}]
set_property PACKAGE_PIN L20 [get_ports {e_txd[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_txd[4]}]
set_property SLEW FAST [get_ports {e_txd[4]}]
set_property DRIVE 12 [get_ports {e_txd[4]}]
set_property PACKAGE_PIN L19 [get_ports {e_txd[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_txd[5]}]
set_property SLEW FAST [get_ports {e_txd[5]}]
set_property DRIVE 12 [get_ports {e_txd[5]}]
set_property PACKAGE_PIN L13 [get_ports {e_txd[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_txd[6]}]
set_property SLEW FAST [get_ports {e_txd[6]}]
set_property DRIVE 12 [get_ports {e_txd[6]}]
set_property PACKAGE_PIN J17 [get_ports {e_txd[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {e_txd[7]}]
set_property SLEW FAST [get_ports {e_txd[7]}]
set_property DRIVE 12 [get_ports {e_txd[7]}]

set_false_path -from [get_ports reset_n] -to [all_registers]
